/**
 * @Author             : Xiang Zheng
 * @Description        : this class is for process builder do nothing action. 
 * @Modification Log   : 
 * ---------------------------------------------------
 * Date           Author      		    Details
 * ---------------------------------------------------
 * 21/07/2021     Xiang Zheng           PBI 302563: Develop the capability to data fix the Account object without an outage
**/
public class DoNothing {
    @InvocableMethod
    public static void doNothing() {}
}